### ISSUE TITLE
请问您可以分享一下您之前的STOIC数据集吗？

### ISSUE THREAD

**Issue by zhongqiu1245** [junqiangchen/PytorchDeepLearing#1]
大神您好！
请问您可以分享一下您之前的STOIC数据集吗？
因为原始的网站链接下载总是断断续续的，请问您可以分享一下您的STOIC数据集吗？panbaidu？
谢谢！

**Comment by junqiangchen** [comment]
您好，原始数据有243G大小，太大了

**Comment by zhongqiu1245** [comment]
好吧，谢谢您的答复

**Comment by JiaZhe1026** [comment]
大神您好 请问可以分享一下数据集的网站链接吗
