### ISSUE TITLE
青光眼那个用的是BinaryResNet2dModel？

### ISSUE THREAD

**Issue by wentixiaogege** [junqiangchen/PytorchDeepLearing#13]
这个配置么？TASK1

    resnet2d = BinaryResNet2dModel(image_height=1024, image_width=1024, image_channel=1, numclass=1,
                                  batch_size=32, loss_name='BinaryCrossEntropyLoss',use_cuda=use_cuda)
    resnet2d.trainprocess(trainimages, trainlabels, valimages, vallabels, model_dir='log/BinaryResNet2d/CE', epochs=300,
                          lr=0.005)

**Comment by junqiangchen** [comment]
@wentixiaogege 可以的，也可以用MutilResNet2dModel
