### ISSUE TITLE
图中放的路径文件是什么，放在哪啊，是不是缺数据集

### ISSUE THREAD

**Issue by Pipaup** [junqiangchen/PytorchDeepLearing#16]
如题,我们小组纯小白，但是课程老师要求我们跑通这个项目，才能放暑假😫😫😫
环境和库都安装好了，但是在运行的时候报错好像缺文件，图中D盘的文件都是啥啊，我好像没有在gitHub上找到
![QQ20240711-152232](https://github.com/junqiangchen/PytorchDeepLearing/assets/54436746/244f590c-7595-4139-9076-f1bb06c49e34)

**Comment by buxingjiabing** [comment]
现在解决了吗，我最近也开始跑这个项目，想有些问题请教你一下
