### ISSUE TITLE
ROI区域代码请教

### ISSUE THREAD

**Issue by DiahannWu** [junqiangchen/PytorchDeepLearing#3]
```由于结节在图像中心位置，且目标比较小，所以根据LIDC-IDRI_1176.npy文件中结节的直径大小，在128x128x64大小上获取肺结节ROI区域图像，这样就可以进一步减少背景干扰，因此得到肺结节的ROI区域。然后统计全部肺结节ROI区域的大小，平均大小是33x33x18。```
请问这里获取ROI区域的代码能分享一下吗

**Comment by junqiangchen** [comment]
ROI是根据直径来计算得到的，很简单

**Comment by DiahannWu** [comment]
这里图像的(128x128x64)已经是对应物理坐标了吗，所以先根据LIDC-IDRI_1176.npy文件中结节的直径大小/spacing得到物理直径，然后roi_image为[64-直径/2:64+直径，64-直径/2:64+直径，32-直径/2:32+直径]吗？

**Comment by junqiangchen** [comment]
@DiahannWu 为了考虑到结节和附近的背景区域，我建议roi_image为[64-直径:64+直径，64-直径:64+直径，32-直径:32+直径]

**Comment by DiahannWu** [comment]
好的，非常感谢大佬

**Comment by DiahannWu** [comment]
> @DiahannWu 为了考虑到结节和附近的背景区域，我建议roi_image为[64-直径:64+直径，64-直径:64+直径，32-直径:32+直径]

好的，非常感谢大佬
