### ISSUE TITLE
请问可以分享ASOCA2020数据集吗？

### ISSUE THREAD

**Issue by 476663616** [junqiangchen/PytorchDeepLearing#4]
我们在比赛官网申请了很多次使用ASOCA2020数据集，但是始终没有得到回复，不知道您是不是可以分享下数据集呢？

**Comment by junqiangchen** [comment]
> 我们在比赛官网申请了很多次使用ASOCA2020数据集，但是始终没有得到回复，不知道您是不是可以分享下数据集呢？

您好，该数据集无法私人分享，可以发邮件给举办方获取，谢谢！！
