### ISSUE TITLE
LUNA22-肺结节分类挑战

### ISSUE THREAD

**Issue by kingjames1155** [junqiangchen/PytorchDeepLearing#5]
看到您LUNA22-肺结节分类挑战的文章，觉得很有意思，文章里说您将代码放在了这里，可我没找到，请问您LUNA22-肺结节分类挑战具体的代码在哪里呢

**Comment by junqiangchen** [comment]
> 看到您LUNA22-肺结节分类挑战的文章，觉得很有意思，文章里说您将代码放在了这里，可我没找到，请问您LUNA22-肺结节分类挑战具体的代码在哪里呢

您好，分类代码可以参考使用model里的modelResNet.py的分类网络，谢谢
