### ISSUE TITLE
ASOCA2020数据集问题

### ISSUE THREAD

**Issue by jinaozhang** [junqiangchen/PytorchDeepLearing#8]
您好，我想问一下您的ASOCA2020数据集的测试集是自己标注的吗？官方提供的是未经过标注的，您方便提供一下标注过的测试集吗？

**Comment by junqiangchen** [comment]
@jinaozhang 官方测试集是没有标注的

**Comment by xiaolinfan** [comment]
您好，请您用WW-WHS和ASOCA是怎么进行结合训练测试，最终可以分割7个子结构和冠状动脉？两个数据集的CT并不相同。

**Comment by junqiangchen** [comment]
@angolin22 您好，模型权重是预训练好的。

**Comment by chuanqiWen** [comment]
您好，我想问一下ASOCA的数据集方便分享嘛？我多次联系了主办方却迟迟得不到回应。

**Comment by whz123** [comment]
您好，我也同求ASOCA的数据集，谢谢

**Comment by junqiangchen** [comment]
> 您好，我也同求ASOCA的数据集，谢谢

请联系举办方获取。

**Comment by junqiangchen** [comment]
> 您好，我想问一下ASOCA的数据集方便分享嘛？我多次联系了主办方却迟迟得不到回应。

可以多发几次右键
