### ISSUE TITLE
有关luna2022的代码请教

### ISSUE THREAD

**Issue by Zhaoyucheng0928** [junqiangchen/PytorchDeepLearing#9]
大神您好，我想请教一下关于从zenodo下载的数据集怎么处理啊？里面是nii型文件，而您的instruction相关的是npy文件，不是太懂这里面的关系。

我看到您的github的 dataprocess  的文件下有个data里面是储存的csv，我看了一些数据处理的代码不太能理解，关于如何从数据集nii到npy到train，validation分类这个步骤不是很懂。能否麻烦大神您给个详细点的步骤。

如果方便的话能麻烦您写一个luna2022数据集分类的代码执行步骤吗，我是初学者，根据您在GitHub上的代码感觉到很难理解

**Comment by junqiangchen** [comment]
@Zhaoyucheng0928 数据处理步骤可以参考这个项目https://github.com/junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge/tree/master
